server:
  port: 8020
spring:
  application:
    name: "movie"
  data:
    mongodb:
      uri: ${MONGODB}/${DB_NAME_MONGO}
    #uri: "mongodb://localhost:27017/movies" #VALOR DE LA VARIABLES DE ENTORNO EN LOCAL -> MONGODB = mongodb://localhost:27017/ -> DB_NAME_MONGO = movies